from dataclasses import dataclass


@dataclass
class PALDecision:
    """
    Final decision generated by PALBrain.
    This is consumed by the Report Engine.
    """

    market_story: str = ""

    mission: str = ""

    trading_focus: str = ""

    action: str = "NO TRADE"

    confidence: int = 0

    next_event: str = ""